<?php
/**
 * @author Mygento
 * @copyright See COPYING.txt for license details.
 * @package Mygento_Payment
 */
?>
<div class="redirect button">
    <form action="<?php echo $block->getPlaceUrl(); ?>" method="post"
          id="<?php echo $block->getCode();?>_redirect_form">
        <?php foreach ($block->getPostData() as $key => $value): ?>
            <input type="hidden" name="<?php echo $key; ?>"
                   value="<?php echo $value; ?>"/>
        <?php endforeach; ?>
        <button id="<?php echo $block->getCode();?>_redirect" type="submit"><?php echo __('Pay');?></button>
        <script type="text/javascript">document.getElementById("<?php echo $block->getCode();?>_redirect_form").submit();</script>
    </form>
</div>