<?php
/**
 * @author Mygento
 * @copyright See COPYING.txt for license details.
 * @package Mygento_Payment
 */
?>
<dl class="payment-method <?php echo $block->getCode(); ?>">
    <dt class="title"><?php echo $block->escapeHtml($block->getMethod()->getTitle()) ?></dt>
</dl>
<p>
    <?php if ($this->isAuthorized()): ?>
        <?php echo $block->escapeHtml(__('Order has authorized sum')); ?>
    <?php elseif (!$this->isPaid() && !$this->isAuthorized()): ?>
        <a target="_blank" href="<?php echo $block->getPaylink(); ?>">
            <?php echo $block->escapeHtml(__('Pay order')); ?>
        </a>
    <?php else: ?>
        <?php echo $block->escapeHtml(__('Order is paid')); ?>
    <?php endif; ?>
</p>